### ISSUE TITLE
screenshots on ankiweb are not shown

### ISSUE THREAD

**Issue by ijgnd** [hgiesel/anki_add_note_id#1]
today at https://ankiweb.net/shared/info/886709118 instead of images I only see placeholders. Not really an issue but still relevant.

**Comment by hgiesel** [comment]
Yep, I uploaded them to GitHub LFS, and now they want to charge me :(

**Comment by hgiesel** [comment]
I uploaded the repo to GitLab as well, and changed the links on the listing to use the GitLab links.

Everybody who's interested can read some more [here](https://medium.com/@megastep/github-s-large-file-storage-is-no-panacea-for-open-source-quite-the-opposite-12c0e16a9a91).
