### ISSUE TITLE
Ze Add Note Id (2.1.28) — Field Order, Visibility, More than one field

### ISSUE THREAD

**Issue by GuitarTab** [hgiesel/anki_add_note_id#3]
Great addon, very useful!

I just updated; a couple of questions came up:

* the *Note ID* field **IS** still visible in the *Add* dialogue
* the first image shows *reposition noteid field as first field*; but the image for *Edit Current* shows the *noteid* field as the **LAST** field … [here](https://ankiweb.net/shared/info/886709118)
* in *Manage Note Types*, it is possible to tick *Insert note id* for several fields at the same time — is there a use case for this?

Greetings!

**Comment by hgiesel** [comment]
> the Note ID field IS still visible in the Add dialogue

This is likely to other add-ons interfering. Do you have by any change "Frozen Fields" installed?

> the first image shows reposition noteid field [...]

Yes, that is something I should correct. The next time I work on this add-on I will take new screenshots. It makes most sense to have the noteid as the first field.

> in Manage Note Types, [...] — is there a use case for this?

I can't really think of one. Due to the general way I wrote the code, it is technically possible. Maybe at some point, other things could be inserted in the fields (a list of associated card ids?), but at this point, I don't see a use case.

**Comment by GuitarTab** [comment]
Thanks for replying!

*Frozen Fields*: yes, it was installed. After disabling it, *Note ID* **IS** gone from the *Add* dialogue. So I guess I should use [Ze Frozen Fields](https://ankiweb.net/shared/info/94610912) instead … **BUT**: I **absolutely** need the **hotkey** `Shift + F9`: *toggle status for all fields*

BTW, why not suppress the *Note ID* field in **ALL** dialogues? There's no need for me to see the *Note ID* field in the *Edit Current* dialogue, or in the Card Browser.

*Manage Note Types*: so maybe you could turn *Insert note id* into a **Radio Button** instead …

Anyway, great addon; should be part of Anki to begin with.

**Comment by hgiesel** [comment]
I can add that hotkey, however probably sometime next week. I'm kinda busy right now, but I'll put in my priority list.

> BTW, why not suppress the Note ID field in ALL dialogues? 

There are users, who use to copy it somewhere (e.g. into their external notes). I could put it as an option though.

**Comment by GuitarTab** [comment]
Hi *hgiesel*, again, thanks very much for your reply.

> I'm kinda busy right now,

Please, take all the time you want, this is not urgent. For the time being, I disabled *Ze Add Note Id* and quickly type something random myself when creating new cards.

> I could put it as an option though.

That would be great; I'd guess most users don't need to see the Note ID …

**Comment by hgiesel** [comment]
@GuitarTab 
I never used that feature on Glutanimates Frozen Fields, so I'm just gonna ask you: How should the "Toggle all fields" shortcut work? 

Would it literally "toggle" all fields, or rather, put all fields uniformly to "unfrozen" or "frozen" state? And unrelated to how it worked before, which one would you find more useful?

Maybe you could also answer under https://github.com/hgiesel/anki_frozen_fields/issues/1, so it's in the right repo
