### ISSUE TITLE
Not working on 2.1.42

### ISSUE THREAD

**Issue by mnhende2** [hgiesel/anki_add_note_id#5]
Anki is not allowing me to save on 2.1.42 when the first field "Note ID" is blank.  I didn't have this previously, are you facing the same problem?  What are you doing to work around to get new cards to save?

**Comment by hgiesel** [comment]
Cannot recreate this. Did you make sure it's not because of add-on interactions?

**Comment by mnhende2** [comment]
I could not figure out what was happening and then I realized that despite previously having thought I updated the addon, it must not have actually updated.  So, I was using an the pre-March 3 version.  Anyhow, it is working now.  Apologies for the inconvenience.

**Comment by hgiesel** [comment]
No worries :)
